version: "3"
services:
  mongo:
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
  frontend:
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
  backend:
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]