version: "3.5"
services:
  mongo:
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
  frontend:
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == manager]
  backend:
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == manager]