---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-realworld
  labels:
    app: realworld
    type: frontend
spec:
  replicas: {{ .Values.replicas.qty }}
  selector:
    matchLabels:
      app: realworld
      type: frontend
  template:
    metadata:
      labels:
        app: realworld
        type: frontend
    spec:
      containers:
        - name: fe-realworld
          image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          env:
            - name: REACT_APP_BACKEND_URL
              value: {{ if ne .Release.Namespace "default" }}{{ .Release.Namespace }}.{{ end }}{{ .Values.env.react_app_backend_url }}
          ports:
            - containerPort: {{ .Values.port }}
          imagePullPolicy: Always