---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-admin
spec:
  rules:
    - host: "adminmongo.realworld.local.io"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: mongo-admin
                port:
                  number: 8082