---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-realworld
  labels:
    app: realworld
    type: mongo
spec:
  serviceName: mongo
  replicas: {{ .Values.mongo.replicas.qty }}
  selector:
    matchLabels:
      app: realworld
      type: mongo
  template:
    metadata:
      labels:
        app: realworld
        type: mongo
    spec:
      volumes:
        - name: mongo-pvc
          persistentVolumeClaim:
            claimName: mongo-pvc
      containers:
        - name: mongo-realworld
          image: mongo:{{ .Values.mongo.image.tag }}
          command: ["mongod"]
          args: ["--smallfiles"]
          ports:
            - containerPort: {{ .Values.mongo.port }}
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /data/db
              name: mongo-pvc