---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: realworld
    type: mongo
spec:
  ports:
    - port: {{ .Values.mongo.port }}
      name: mongo
  clusterIP: None
  selector:
    app: realworld
    type: mongo