---
galaxy_info:
  role_name: nginx
  author: me
  description: example_nginx
  company: hillel
  license: GPL-2.0-or-later
  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - all
