---
- name: Check && install python
  hosts: all
  become: true
  gather_facts: false

  vars:
    app_root: ../sample_html_site

  roles:
    - nginx

  tasks:
    - name: Copy website files to the server's document root
      ansible.posix.synchronize:
        src: "{{ app_root }}/"
        dest: "{{ document_root }}"
        checksum: true
        times: false
        delete: true
      tags: deploy
